set nocompatible              " be iMproved, required
filetype off                  " required

call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'mileszs/ack.vim'
Plug 'tpope/vim-fugitive'
Plug 'kien/ctrlp.vim'
Plug 'morhetz/gruvbox'
Plug 'chriskempson/base16-vim'
call plug#end()

syn on
filetype plugin indent on
set expandtab
" set foldmethod=syntax
set guioptions-=T
set listchars=eol:$,tab:>-,trail:.
set nohlsearch
set nonumber
set smartindent
set cinoptions+=(0
set laststatus=2
set t_Co=256

filetype plugin on
