set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

Plugin 'gmarik/Vundle.vim'      " required

Plugin 'scrooloose/nerdtree'
Plugin 'mileszs/ack.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim'
Plugin 'morhetz/gruvbox'

call vundle#end()               " required

syn on
filetype plugin indent on
set expandtab
" set foldmethod=syntax
set guioptions-=T
set listchars=eol:$,tab:>-,trail:.
set nohlsearch
set nonumber
set smartindent
set cinoptions+=(0
set laststatus=2
set t_Co=256

filetype plugin on
